/**
 * Hand-built topographic card art — overlapping organic "elevation" rings
 * generated by warping concentric ellipses through an SVG turbulence
 * displacement filter. Renders as an absolute-positioned SVG meant to sit
 * inside a card container.
 */
export default function TopoPattern({ className = '' }) {
  return (
    <svg
      className={className}
      viewBox="0 0 1200 700"
      preserveAspectRatio="xMidYMid slice"
      aria-hidden="true"
    >
      <defs>
        {/* Slight organic warp for the contour rings */}
        <filter
          id="topo-warp"
          x="-10%"
          y="-10%"
          width="120%"
          height="120%"
          filterUnits="userSpaceOnUse"
        >
          <feTurbulence
            type="fractalNoise"
            baseFrequency="0.006"
            numOctaves="2"
            seed="7"
          />
          <feDisplacementMap in="SourceGraphic" scale="55" />
        </filter>

        {/* Stronger warp for the looser dashed rings */}
        <filter
          id="topo-warp-soft"
          x="-15%"
          y="-15%"
          width="130%"
          height="130%"
          filterUnits="userSpaceOnUse"
        >
          <feTurbulence
            type="fractalNoise"
            baseFrequency="0.004"
            numOctaves="2"
            seed="3"
          />
          <feDisplacementMap in="SourceGraphic" scale="80" />
        </filter>
      </defs>

      {/* Solid contour group — three overlapping centers */}
      <g
        stroke="var(--palette-red)"
        fill="none"
        strokeWidth="1.5"
        filter="url(#topo-warp)"
      >
        {/* Center A — upper left */}
        <g>
          <ellipse cx="260" cy="200" rx="220" ry="150" opacity="0.85" />
          <ellipse cx="260" cy="200" rx="190" ry="130" opacity="0.78" />
          <ellipse cx="260" cy="200" rx="160" ry="110" opacity="0.72" />
          <ellipse cx="260" cy="200" rx="130" ry="90" opacity="0.65" />
          <ellipse cx="260" cy="200" rx="100" ry="68" opacity="0.58" />
          <ellipse cx="260" cy="200" rx="72" ry="48" opacity="0.5" />
        </g>

        {/* Center B — lower right */}
        <g>
          <ellipse cx="920" cy="500" rx="300" ry="220" opacity="0.9" />
          <ellipse cx="920" cy="500" rx="260" ry="195" opacity="0.82" />
          <ellipse cx="920" cy="500" rx="220" ry="170" opacity="0.74" />
          <ellipse cx="920" cy="500" rx="180" ry="140" opacity="0.66" />
          <ellipse cx="920" cy="500" rx="140" ry="110" opacity="0.58" />
          <ellipse cx="920" cy="500" rx="100" ry="80" opacity="0.5" />
          <ellipse cx="920" cy="500" rx="62" ry="52" opacity="0.42" />
        </g>

        {/* Center C — middle */}
        <g>
          <ellipse cx="580" cy="340" rx="260" ry="190" opacity="0.78" />
          <ellipse cx="580" cy="340" rx="225" ry="165" opacity="0.7" />
          <ellipse cx="580" cy="340" rx="190" ry="140" opacity="0.62" />
          <ellipse cx="580" cy="340" rx="155" ry="115" opacity="0.55" />
          <ellipse cx="580" cy="340" rx="120" ry="90" opacity="0.48" />
        </g>
      </g>

      {/* Dashed background contours — looser silver, lower opacity */}
      <g
        stroke="#d4d4d8"
        fill="none"
        strokeWidth="1.1"
        strokeDasharray="4 6"
        opacity="0.45"
        filter="url(#topo-warp-soft)"
      >
        {/* Bottom-left blob */}
        <ellipse cx="160" cy="600" rx="320" ry="170" />
        <ellipse cx="160" cy="600" rx="290" ry="150" />
        <ellipse cx="160" cy="600" rx="260" ry="130" />
        <ellipse cx="160" cy="600" rx="230" ry="110" />

        {/* Top-right blob */}
        <ellipse cx="1050" cy="120" rx="340" ry="180" />
        <ellipse cx="1050" cy="120" rx="300" ry="160" />
        <ellipse cx="1050" cy="120" rx="260" ry="140" />
        <ellipse cx="1050" cy="120" rx="220" ry="120" />
      </g>
    </svg>
  )
}
